# Generated by Django 4.2.7 on 2023-12-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=15)),
                ('delivered_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
