# Generated by Django 3.2 on 2023-11-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('delivery_number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=15)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.order')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.receiver')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
    ]
