# Generated by Django 4.2.7 on 2023-12-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('delivery_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
