# Generated by Django 3.2 on 2023-11-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('staff', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryReceipt',
            new_name='Delivery',
        ),
    ]
