# Generated by Django 4.2.7 on 2023-12-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.ordereditem'),
        ),
    ]
