# Generated by Django 3.2 on 2023-11-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
        ('delivery', '0002_rename_deliveryreceipt_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='items',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.ordereditem'),
            preserve_default=False,
        ),
    ]
