# Generated by Django 4.2.7 on 2023-12-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInventory',
            fields=[
                ('batch_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('issue_time', models.TimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('issuer_number', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('staff_first_name', models.CharField(max_length=300)),
                ('staff_last_name', models.CharField(max_length=300)),
                ('staff_phone_number', models.IntegerField()),
                ('staff_type', models.CharField(choices=[('Regular', 'Regular'), ('Issuer', 'Issuer'), ('Receiver', 'Receiver')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transfer_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('receiver_batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_batch_number', to='staff.batchinventory')),
                ('source_batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_batch_number', to='staff.batchinventory')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.issuance')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('receiver_number', models.AutoField(primary_key=True, serialize=False)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.receiver')),
            ],
        ),
    ]
