# Generated by Django 4.2.7 on 2023-11-26 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('staff_first_name', models.CharField(max_length=300)),
                ('staff_last_name', models.CharField(max_length=300)),
                ('staff_phone_number', models.IntegerField()),
                ('staff_type', models.CharField(choices=[('Regular', 'Regular'), ('Issuer', 'Issuer'), ('Receiver', 'Receiver')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('receiver_number', models.AutoField(primary_key=True, serialize=False)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('issuer_number', models.AutoField(primary_key=True, serialize=False)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
    ]
