# Generated by Django 4.2.7 on 2023-11-27 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IssuedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item_brand', models.CharField(max_length=300)),
                ('item_model', models.CharField(max_length=300)),
                ('item_qty', models.IntegerField()),
                ('item_type', models.CharField(choices=[('Timepieces', 'Timepieces'), ('Digital Cameras and Accessories', 'Digital Cameras and Accessories'), ('Mobile Phones', 'Mobile Phones'), ('Small Appliances', 'Small Appliances')], max_length=300)),
                ('item_cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('item_SRP', models.DecimalField(decimal_places=3, max_digits=10)),
                ('item_total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_type_name', models.CharField(choices=[('Timepieces', 'Timepieces'), ('Digital Cameras and Accessories', 'Digital Cameras and Accessories'), ('Mobile Phones', 'Mobile Phones'), ('Small Appliances', 'Small Appliances')], max_length=300)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_quantity', models.IntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.IntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField()),
                ('order_total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
