# Generated by Django 4.2.7 on 2023-12-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IssuedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_quantity', models.IntegerField()),
                ('item_discount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('issued_SRP', models.DecimalField(decimal_places=3, max_digits=10)),
                ('item_type', models.CharField(choices=[('Timepieces', 'Timepieces'), ('Digital Cameras and Accessories', 'Digital Cameras and Accessories'), ('Mobile Phones', 'Mobile Phones'), ('Small Appliances', 'Small Appliances')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item_brand', models.CharField(max_length=300)),
                ('item_model', models.CharField(max_length=300)),
                ('item_qty', models.IntegerField()),
                ('item_cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('item_total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('item_type', models.CharField(choices=[('Timepieces', 'Timepieces'), ('Digital Cameras and Accessories', 'Digital Cameras and Accessories'), ('Mobile Phones', 'Mobile Phones'), ('Small Appliances', 'Small Appliances')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Timepieces', 'Timepieces'), ('Digital Cameras and Accessories', 'Digital Cameras and Accessories'), ('Mobile Phones', 'Mobile Phones'), ('Small Appliances', 'Small Appliances')], max_length=300)),
                ('item_discount', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField()),
                ('order_total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('supplier_item_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('supplier_item_brand', models.CharField(max_length=300)),
                ('supplier_item_model', models.CharField(max_length=300)),
                ('supplier_item_qty', models.IntegerField()),
                ('supplier_item_type', models.CharField(choices=[('Timepieces', 'Timepieces'), ('Digital Cameras and Accessories', 'Digital Cameras and Accessories'), ('Mobile Phones', 'Mobile Phones'), ('Small Appliances', 'Small Appliances')], max_length=300)),
                ('supplier_item_cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('supplier_item_total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
            ],
        ),
    ]
