# Generated by Django 4.2.7 on 2023-12-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('agent', '0001_initial'),
        ('supplier', '0001_initial'),
        ('items', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferreditem',
            name='transfer_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.transfer'),
        ),
        migrations.AddField(
            model_name='supplieritem',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='invoice_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.sales'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.issueditem'),
        ),
        migrations.AddField(
            model_name='returneditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.issueditem'),
        ),
        migrations.AddField(
            model_name='returneditem',
            name='return_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.return'),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.supplieritem'),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.order'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='item_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='issueditem',
            name='batch_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_items', to='staff.batchinventory'),
        ),
        migrations.AddField(
            model_name='issueditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='issueditem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemtype'),
        ),
        migrations.AddField(
            model_name='delivereditem',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_items', to='supplier.delivery'),
        ),
        migrations.AddField(
            model_name='delivereditem',
            name='ordered_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ordereditem'),
        ),
    ]
