# Generated by Django 4.2.7 on 2023-12-02 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('agent_first_name', models.CharField(max_length=300)),
                ('agent_last_name', models.CharField(max_length=300)),
                ('agent_phone_number', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
