# Generated by Django 4.2.7 on 2023-12-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agent.agent'),
        ),
    ]
