# Generated by Django 4.2.7 on 2023-11-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('supplier_phone_number', models.CharField(max_length=300)),
            ],
        ),
    ]
