# Generated by Django 4.2.7 on 2023-12-01 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('supplier_phone_number', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('delivery_time', models.TimeField(auto_now_add=True)),
                ('delivered_items', models.ManyToManyField(related_name='deliveries', to='items.delivereditem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_items', to='staff.order')),
            ],
        ),
    ]
