# Generated by Django 3.2 on 2023-11-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('items', '0002_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('delivery_time', models.TimeField(auto_now_add=True)),
                ('delivered_items', models.ManyToManyField(related_name='orders', to='items.DeliveredItem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_items', to='staff.order')),
            ],
        ),
    ]
