# Generated by Django 3.2 on 2023-12-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
        ('supplier', '0002_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivered_items',
            field=models.ManyToManyField(related_name='deliveries', to='items.OrderedItem'),
        ),
    ]
